version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install aws-cli and sam to build the project
      - pip install -U aws-sam-cli pytest pytest-mock

  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - python -m pytest tests/ -v
  
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build --template template.yaml
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - beta-configuration.json
