AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  autoblock bot

  Telegram bot that implements a blacklist and a whitelist

Resources:
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
        - AttributeName: "role_users_pk"
          AttributeType: "S"
        - AttributeName: "role_users_sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: role_users
          KeySchema:
            - AttributeName: "role_users_pk"
              KeyType: "HASH"
            - AttributeName: "role_users_sk"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ScraperOutputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  AutoBlockFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: autoblock_function/
      Handler: autoblock.app.lambda_handler
      Runtime: python3.7
      MemorySize: 256
      Timeout: 60
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5minutes
        Alarms:
          - !Ref AutoBlockErrorAlarm
          - !Ref AutoBlockDurationAlarm
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RolesTable
        - S3ReadPolicy:
            BucketName: !Ref ScraperOutputBucket
        - CloudWatchPutMetricPolicy: {}
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          ROLE_TABLE_NAME: !Ref RolesTable
          ROLE_USERS_INDEX: role_users
          OUTPUT_BUCKET_NAME: !Ref ScraperOutputBucket
          APP_CONFIG_PATH: '/autoblock_bot'
      Events:
        WebHook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post
        Whitelist:
          Type: Api
          Properties:
            Path: /whitelist
            Method: post
        Blacklist:
          Type: Api
          Properties:
            Path: /blacklist
            Method: post

  BlocklistScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: autoblock_function/
      Handler: autoblock.blocklist_scraper.lambda_handler
      Runtime: python3.7
      MemorySize: 512
      Timeout: 900
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RolesTable
        - S3CrudPolicy:
            BucketName: !Ref ScraperOutputBucket
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          ROLE_TABLE_NAME: !Ref RolesTable
          ROLE_USERS_INDEX: role_users
          OUTPUT_BUCKET_NAME: !Ref ScraperOutputBucket

  AutoScrapeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Periodically scrape the blocked users list"
      ScheduleExpression: rate(7 days)
      State: ENABLED
      Targets:
        - Arn: !GetAtt BlocklistScraperFunction.Arn
          Id: BlocklistScraperTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BlocklistScraperFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AutoScrapeRule.Arn

  AlarmPagerTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      DisplayName: autoblock-bot-pager
      KmsMasterKeyId: aws/kms

  AutoBlockErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: More than zero autoblock lambda execution failures
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 0
      ThresholdMetricId: AutoBlockErrors
      TreatMissingData: notBreaching
      Metrics:
        - Id: AutoBlockErrors
          Label: AutoBlock lambda failures
          MetricStat:
            Metric:
              Metric:
                Namespace: AWS/Lambda
                Dimensions:
                  - Name: FunctionName
                    Value: !Ref AutoBlockFunction
                MetricName: Errors
              Period: 300
              Stat: Sum
              Unit: Count

  AutoBlockDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Any execution longer than 30 seconds
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 30000 # 30 seconds
      ThresholdMetricId: AutoBlockDuration
      TreatMissingData: notBreaching
      Metrics:
        - Id: AutoBlockDuration
          Label: Autoblock execution duration
          MetricStat:
            Metric:
              Namespace: AWS/Lambda
              Dimensions:
                - Name: FunctionName
                  Value: !Ref AutoBlockFunction
              MetricName: Duration
            Period: 300
            Stat: Maximum
            Unit: Milliseconds

  BlocklistScraperErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: More than zero blocklist scraper lambda execution failures
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 0
      ThresholdMetricId: BlocklistScraperErrors
      TreatMissingData: notBreaching
      Metrics:
        - Id: BlocklistScraperErrors
          Label: BlocklistScraper lambda failures
          MetricStat:
            Metric:
              Metric:
                Namespace: AWS/Lambda
                Dimensions:
                  - Name: FunctionName
                    Value: !Ref BlocklistScraperFunction
                MetricName: Errors
              Period: 300
              Stat: Sum
              Unit: Count

  BlocklistScraperDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Any execution longer than 5 minutes
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 300000 # 5 minutes
      ThresholdMetricId: BlocklistScraperDuration
      TreatMissingData: notBreaching
      Metrics:
        - Id: BlocklistScraperDuration
          Label: Autoblock execution duration
          MetricStat:
            Metric:
              Namespace: AWS/Lambda
              Dimensions:
                - Name: FunctionName
                  Value: !Ref BlocklistScraperFunction
              MetricName: Duration
            Period: 300
            Stat: Maximum
            Unit: Milliseconds

  ApiGatewayVolumeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: More than 150 requests within five minutes
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 150
      ThresholdMetricId: ApiGatewayVolume
      TreatMissingData: notBreaching
      Metrics:
        - Id: ApiGatewayVolume
          Label: Api Gateway request volume
          MetricStat:
            Metric:
              Namespace: AWS/ApiGateway
              Dimensions:
                - Name: ApiName
                  Value: autoblock-bot
              MetricName: Count
            Period: 300
            Stat: Sum
            Unit: Count

  DynamoDBReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: More than 2 read capacity units utilized
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 2
      ThresholdMetricId: ReadCapacity
      TreatMissingData: notBreaching
      Metrics:
        - Id: ReadCapacity
          Label: DynamoDB read capacity used
          MetricStat:
            Metric:
              Namespace: AWS/DynamoDB
              Dimensions:
                - Name: TableName
                  Value: !Ref RolesTable
              MetricName: ConsumedReadCapacityUnits
            Period: 300
            Stat: Maximum
            Unit: Count

  DynamoDBWriteCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: More than 2 write capacity units utilized
      AlarmActions:
        - !Ref AlarmPagerTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Threshold: 2
      ThresholdMetricId: WriteCapacity
      TreatMissingData: notBreaching
      Metrics:
        - Id: WriteCapacity
          Label: DynamoDB write capacity used
          MetricStat:
            Metric:
              Namespace: AWS/DynamoDB
              Dimensions:
                - Name: TableName
                  Value: !Ref RolesTable
              MetricName: ConsumedWriteCapacityUnits
            Period: 300
            Stat: Maximum
            Unit: Count

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AutoBlockApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  AutoBlockFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AutoBlockFunction.Arn
  AutoBlockFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AutoBlockFunctionRole.Arn
  RolesTable:
    Description: "DynamoDB table containing role associations"
    Value: !GetAtt RolesTable.Arn
